fail_fast: true

repos:

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff-format
        args: [custom_components, ag_grid_demo]
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
        exclude: '^integration/benchmarks/'

